name: release
on:
  release:
    types: [published]

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: installing JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'prepare gradle'
        uses: gradle/gradle-build-action@v2
      - id: get-version
        run: |
          echo "version=$(echo $(basename ${{github.ref}}))" >> $GITHUB_OUTPUT
      - name: 'run gradle frontend'
        shell: bash
        run: |
          ./gradlew :frontend:assemble -Pversion=${{ steps.get-version.outputs.version }}
      - name: 'run gradle'
        shell: bash
        run: |
          ./gradlew jib -Pversion=${{ steps.get-version.outputs.version }} \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.REPO_TOKEN }}